### PR TITLE
Remove proof of control signature

### PR DESCRIPTION
**Pull request by hbergren**
## High Level Overview of Change

The Proof of Control Signature serves no purpose and is entirely unused, so we should remove it.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by Stormtv** [comment]
@hbergren Is the burden on the admin of the PayID server to implement proper verifications to ensure ownership of the addresses that users register? Also does PayID allow a single address to be mapped to multiple PayIDs?

**Comment by hbergren** [comment]
> @hbergren Is the burden on the admin of the PayID server to implement proper verifications to ensure ownership of the addresses that users register?

What harm is there to you if I register your address? Someone sends me money... and you get paid? I don't really see a threat model there.

> Also does PayID allow a single address to be mapped to multiple PayIDs?

Yup, it's entirely decentralized, so you could register a single crypto address with multiple PayID servers, and there's nothing wrong with that.

**Comment by Stormtv** [comment]
@hbergren The concern I had was whether someone could register my address to say `terribleperson$xpring.money` would I still be able to register it to `stormtv$xpring.money` which is the same PayID domain? If that is true then performing a lookup of what PayID is registered to a given address on `xpring.money` could result in multiple PayIDs making it hard to associate a singular identity to an address in a UI.

**Comment by hbergren** [comment]
> @hbergren The concern I had was whether someone could register my address to say terribleperson$xpring.money would I still be able to register it to stormtv$xpring.money (which is the same PayID server)? If that is true then performing a lookup of what PayID is registered to a given address on xpring.money could result in multiple PayIDs making it hard to associate a singular identity to an address in a UI.

In the reference implementation, we don't currently do any checks on the address part of the payload. You can give us garbage, and we'll serve it, and there's no unique constraint on address stuff.

PayID isn't really designed to do a lookup from address => PayID, and I'm not sure how useful that is. I've seen requests for a way to store metadata on the XRPL with your account to point to a specific PayID from an XRPL address, but I don't think we did anything on that subject.

Ideally, we live in a world where you never even know what your ledger addresses are (the same way that because of 1Password, I don't know what any of my passwords are). You just have a PayID and give that out. Does that make sense? Or am I missing some scenario where the reverse lookup (address => PayID) is useful?

**Pull request merged**
